// Session & Agent State Manifest
//
// Generated by scripts/gen-state-manifest.mts — do not edit by hand.
// Regenerate with: pnpm --filter @dimi-ai/agent-core-v2 gen:state-manifest
//
// Every state key registered into the Session-scope ISessionStateService or the
// Agent-scope IAgentStateService (see src/_base/state/stateRegistry.ts), collected
// statically from the `states.register(...)` call sites — a key defined via
// defineState but never registered does not appear here. Each entry shows the
// compile-time StateKey<T> value type fully expanded inline, so the manifest is
// self-contained (no imports, no helper declarations). A named type is marked
// at its expansion site with a `/* TypeName — source/file.ts */` comment; a
// `/* TypeName — recursive (...) */ unknown` marker stops a recursive expansion.
// Lib globals (Map/Set/Record/…) are referenced as-is. Generic instantiations
// expand structurally; classes render as their public instance shape. The
// defining source file heads each group.
//
// External ambient types referenced but not expanded (from node_modules): Readable, Writable
//
// snapshot() returns JSON-safe deep copies of these values: Maps become plain
// objects (or [key, value] entry arrays when a key is not string/number), Sets
// become arrays, bigints become strings, functions are dropped, circular
// references become '(circular)', and class instances collapse to a '(ClassName)'
// marker — the wire shape of an entry is the JSON projection of the type here.
//
// Index (Session: 28 keys · Agent: 68 keys)
//   Session
//     cron.inFlight                             src/session/cron/sessionCronServiceImpl.ts
//     cron.lastSeenAt                           src/session/cron/sessionCronServiceImpl.ts
//     cron.parsedCache                          src/session/cron/sessionCronServiceImpl.ts
//     cron.seededFromStore                      src/session/cron/sessionCronServiceImpl.ts
//     cron.started                              src/session/cron/sessionCronServiceImpl.ts
//     cron.tasks                                src/session/cron/sessionCronServiceImpl.ts
//     interaction.nextId                        src/session/interaction/interactionService.ts
//     interaction.pending                       src/session/interaction/interactionService.ts
//     interaction.recentlyResolved              src/session/interaction/interactionService.ts
//     sessionActivity.current                   src/session/sessionActivity/sessionActivityService.ts
//     sessionActivity.folds                     src/session/sessionActivity/sessionActivityService.ts
//     sessionAgentProfileCatalog.contributions  src/session/sessionAgentProfileCatalog/sessionAgentProfileCatalogService.ts
//     sessionAgentProfileCatalog.merged         src/session/sessionAgentProfileCatalog/sessionAgentProfileCatalogService.ts
//     sessionFs.realRootsCache                  src/session/sessionFs/fsService.ts
//     sessionFs.rgResolution                    src/session/sessionFs/fsService.ts
//     sessionFsWatch.gitignoreLoaded            src/session/sessionFs/fsWatchService.ts
//     sessionFsWatch.pending                    src/session/sessionFs/fsWatchService.ts
//     sessionFsWatch.rawCount                   src/session/sessionFs/fsWatchService.ts
//     sessionFsWatch.truncated                  src/session/sessionFs/fsWatchService.ts
//     sessionFsWatch.watched                    src/session/sessionFs/fsWatchService.ts
//     sessionLog.rootLevel                      src/session/sessionLog/sessionLogService.ts
//     sessionMetadata.data                      src/session/sessionMetadata/sessionMetadataService.ts
//     sessionSkillCatalog.contributions         src/session/sessionSkillCatalog/skillCatalogService.ts
//     sessionSkillCatalog.merged                src/session/sessionSkillCatalog/skillCatalogService.ts
//     sessionToolPolicy.state                   src/session/sessionToolPolicy/sessionToolPolicyService.ts
//     workspaceCommand.pendingMainInjections    src/session/workspaceCommand/workspaceCommandService.ts
//     workspaceContext.additionalDirs           src/session/workspaceContext/workspaceContextService.ts
//     workspaceContext.workDir                  src/session/workspaceContext/workspaceContextService.ts
//   Agent
//     activityView.background                         src/agent/activityView/activityViewService.ts
//     activityView.current                            src/agent/activityView/activityViewService.ts
//     activityView.lastTurn                           src/agent/activityView/activityViewService.ts
//     activityView.lifecycle                          src/agent/activityView/activityViewService.ts
//     activityView.turn                               src/agent/activityView/activityViewService.ts
//     contextInjector.isNewTurn                       src/agent/contextInjector/contextInjectorService.ts
//     contextProjector.lastRepairSignature            src/agent/contextProjector/contextProjectorService.ts
//     contextSize.lastEmittedTokens                   src/agent/contextSize/contextSizeService.ts
//     externalHooks.stopHookContinuationUsed          src/agent/externalHooks/externalHooksService.ts
//     faultInjection.armed                            src/agent/faultInjection/faultInjectionService.ts
//     faultInjection.fired                            src/agent/faultInjection/faultInjectionService.ts
//     fullCompaction.activeTurnId                     src/agent/fullCompaction/fullCompactionService.ts
//     fullCompaction.compactionCountInTurn            src/agent/fullCompaction/fullCompactionService.ts
//     fullCompaction.consecutiveOverflowCompactions   src/agent/fullCompaction/fullCompactionService.ts
//     fullCompaction.lastCompactedTokenCount          src/agent/fullCompaction/fullCompactionService.ts
//     fullCompaction.observedMaxContextTokensByModel  src/agent/fullCompaction/fullCompactionService.ts
//     goal.budgetGraceTurns                           src/agent/goal/goalService.ts
//     goal.countedGoalTurns                           src/agent/goal/goalService.ts
//     goal.exhaustedTurnBudgetGoals                   src/agent/goal/goalService.ts
//     goal.goalDrivenTurns                            src/agent/goal/goalService.ts
//     goal.goalOutcomeContinuationTurns               src/agent/goal/goalService.ts
//     goal.goalOutcomeToolResultTurns                 src/agent/goal/goalService.ts
//     goal.goalStarterTurns                           src/agent/goal/goalService.ts
//     goal.goalTurnTargets                            src/agent/goal/goalService.ts
//     goal.liveTurnId                                 src/agent/goal/goalService.ts
//     goal.liveWallClockStartedAt                     src/agent/goal/goalService.ts
//     goal.pendingContinuationGoals                   src/agent/goal/goalService.ts
//     goal.resumeContinuation                         src/agent/goal/goalService.ts
//     llmRequester.emittedThinkingEffortWarnings      src/agent/llmRequester/llmRequesterService.ts
//     llmRequester.lastConfigLogSignature             src/agent/llmRequester/llmRequesterService.ts
//     llmRequester.mediaDegradedTurns                 src/agent/llmRequester/llmRequesterService.ts
//     llmRequester.mediaStrippedTurns                 src/agent/llmRequester/llmRequesterService.ts
//     llmRequester.turnConfigs                        src/agent/llmRequester/llmRequesterService.ts
//     loop.disposing                                  src/agent/loop/loopService.ts
//     loop.lastRequestTraceId                         src/agent/loop/loopService.ts
//     loop.nextReservedTurnId                         src/agent/loop/loopService.ts
//     mcp.discoveryWritesReady                        src/agent/mcp/mcpService.ts
//     mcp.mcpToolsByServer                            src/agent/mcp/mcpService.ts
//     media.registeredKey                             src/agent/media/mediaToolsRegistrar.ts
//     permissionMode.lastMode                         src/agent/permissionMode/injection/permissionModeInjection.ts
//     plan.wasActive                                  src/agent/plan/injection/planModeInjection.ts
//     profile.activeToolNamesOverlay                  src/agent/profile/profileService.ts
//     profile.agentsMdWarning                         src/agent/profile/profileService.ts
//     profile.emittedPluginBudgetWarnings             src/agent/profile/profileService.ts
//     profile.emittedThinkingEffortWarnings           src/agent/profile/profileService.ts
//     profile.emittedToolPatternWarnings              src/agent/profile/profileService.ts
//     prompt.launching                                src/agent/prompt/promptService.ts
//     shellCommand.tasks                              src/agent/shellCommand/shellCommandService.ts
//     stepRetry.failedAttempts                        src/agent/stepRetry/stepRetryService.ts
//     stepRetry.lastFailedDriverId                    src/agent/stepRetry/stepRetryService.ts
//     task.activeTaskReminderPending                  src/agent/task/taskService.ts
//     task.deliveredNotificationKeys                  src/agent/task/taskService.ts
//     task.ghosts                                     src/agent/task/taskService.ts
//     task.scheduledNotificationKeys                  src/agent/task/taskService.ts
//     toolDedupe.activeStep                           src/agent/toolDedupe/toolDedupeService.ts
//     toolDedupe.activeTurnId                         src/agent/toolDedupe/toolDedupeService.ts
//     toolDedupe.callKeyByCallId                      src/agent/toolDedupe/toolDedupeService.ts
//     toolDedupe.consecutiveCount                     src/agent/toolDedupe/toolDedupeService.ts
//     toolDedupe.consecutiveKey                       src/agent/toolDedupe/toolDedupeService.ts
//     toolDedupe.originalCallIndex                    src/agent/toolDedupe/toolDedupeService.ts
//     toolDedupe.stepCalls                            src/agent/toolDedupe/toolDedupeService.ts
//     toolDedupe.syntheticCallIds                     src/agent/toolDedupe/toolDedupeService.ts
//     toolExecutor.dupTypeTurnId                      src/agent/toolExecutor/toolExecutorService.ts
//     toolExecutor.toolCallDupTypes                   src/agent/toolExecutor/toolExecutorService.ts
//     toolSelect.needsBoundaryInjection               src/agent/toolSelect/toolSelectAnnouncementsService.ts
//     toolSelect.pendingLoaded                        src/agent/toolSelect/toolSelectService.ts
//     usage.currentTurn                               src/agent/usage/usageService.ts
//     usage.currentTurnId                             src/agent/usage/usageService.ts

/** Session-scope keys registered into ISessionStateService. */
export interface SessionStateSnapshot {
  // src/session/cron/sessionCronServiceImpl.ts
  'cron.inFlight': Set<string>;
  'cron.lastSeenAt': Map<string, number>;
  'cron.parsedCache': Map<string, /* ParsedCronExpression — packages/agent-core-v2/src/app/cron/cron-expr.ts */ {
    readonly raw: string;
    readonly minutes: ReadonlySet<number>;
    readonly hours: ReadonlySet<number>;
    readonly daysOfMonth: ReadonlySet<number>;
    readonly months: ReadonlySet<number>;
    readonly daysOfWeek: ReadonlySet<number>;
    readonly daysOfMonthWildcard: boolean;
    readonly daysOfWeekWildcard: boolean;
  }>;
  'cron.seededFromStore': Set<string>;
  'cron.started': boolean;
  'cron.tasks': Map<string, /* CronTask — packages/agent-core-v2/src/app/cron/cronTask.ts */ {
    readonly id: string;
    readonly cron: string;
    readonly prompt: string;
    readonly createdAt: number;
    readonly recurring?: boolean;
    readonly lastFiredAt?: number;
    readonly tags?: Readonly<Record<string, string>>;
  }>;
  // src/session/interaction/interactionService.ts
  'interaction.nextId': number;
  'interaction.pending': Map<string, /* Pending — packages/agent-core-v2/src/session/interaction/interactionService.ts */ {
    readonly interaction: {
      readonly id: string;
      readonly kind: /* InteractionKind — packages/agent-core-v2/src/session/interaction/interaction.ts */ 'approval' | 'question' | 'user_tool';
      readonly payload: unknown;
      readonly origin: /* InteractionOrigin — packages/agent-core-v2/src/session/interaction/interaction.ts */ {
        readonly agentId?: string;
        readonly turnId?: number;
      };
      readonly createdAt: number;
    };
    readonly resolve: (response: unknown) => void;
  }>;
  'interaction.recentlyResolved': Map<string, number>;
  // src/session/sessionActivity/sessionActivityService.ts
  'sessionActivity.current': /* SessionActivityState — packages/agent-core-v2/src/session/sessionActivity/sessionActivity.ts */ {
    readonly busy: boolean;
    readonly mainTurnActive: boolean;
    readonly pendingInteraction: /* SessionPendingInteraction — packages/agent-core-v2/src/session/sessionActivity/sessionActivity.ts */ 'approval' | 'question' | 'none';
    readonly lastTurnReason?: 'completed' | 'cancelled' | 'failed';
  };
  'sessionActivity.folds': Map<string, /* AgentWorkFold — packages/agent-core-v2/src/session/sessionActivity/sessionActivityService.ts */ {
    turnActive: boolean;
    background: number;
    lastTurnReason?: 'completed' | 'cancelled' | 'failed';
  }>;
  // src/session/sessionAgentProfileCatalog/sessionAgentProfileCatalogService.ts
  'sessionAgentProfileCatalog.contributions': Map<string, {
    readonly c: /* AgentProfileContribution — packages/agent-core-v2/src/app/agentFileCatalog/agentProfileSource.ts */ {
      readonly profiles: readonly /* AgentProfile — packages/agent-core-v2/src/app/agentProfileCatalog/agentProfileCatalog.ts */ {
        readonly name: string;
        readonly description?: string;
        readonly whenToUse?: string;
        readonly override?: boolean;
        readonly tools?: readonly string[];
        readonly disallowedTools?: readonly string[];
        readonly subagents?: readonly string[];
        readonly modelPreference?: 'primary' | 'secondary';
        systemPrompt: (context: /* AgentProfileContext — packages/agent-core-v2/src/app/agentProfileCatalog/agentProfileCatalog.ts */ {
          readonly cwd?: string;
          readonly cwdListing?: string;
          readonly agentsMd?: string;
          readonly additionalDirsInfo?: string;
          readonly osKind?: string;
          readonly shellName?: string;
          readonly shellPath?: string;
          readonly now?: string;
          readonly skills?: string;
          readonly skillActive?: boolean;
          readonly pluginSections?: string;
          [key: string]: unknown;
        }) => string;
        readonly promptPrefix?: (ctx: /* AgentProfilePromptPrefixContext — packages/agent-core-v2/src/app/agentProfileCatalog/agentProfileCatalog.ts */ {
          readonly cwd: string;
          readonly runner: /* ISessionProcessRunner — packages/agent-core-v2/src/session/process/processRunner.ts */ {
            readonly _serviceBrand: undefined;
            exec: (args: readonly string[], options?: /* ProcessExecOptions — packages/agent-core-v2/src/session/process/processRunner.ts */ {
              readonly cwd?: string;
              readonly env?: Record<string, string>;
            }) => Promise</* IProcess — packages/agent-core-v2/src/session/process/processRunner.ts */ {
              readonly stdin: Writable;
              readonly stdout: Readable;
              readonly stderr: Readable;
              readonly pid: number;
              readonly exitCode: number | null;
              wait: () => Promise<number>;
              kill: (signal?: 'SIGABRT' | 'SIGALRM' | 'SIGBUS' | 'SIGCHLD' | 'SIGCONT' | 'SIGFPE' | 'SIGHUP' | 'SIGILL' | 'SIGINT' | 'SIGIO' | 'SIGIOT' | 'SIGKILL' | 'SIGPIPE' | 'SIGPOLL' | 'SIGPROF' | 'SIGPWR' | 'SIGQUIT' | 'SIGSEGV' | 'SIGSTKFLT' | 'SIGSTOP' | 'SIGSYS' | 'SIGTERM' | 'SIGTRAP' | 'SIGTSTP' | 'SIGTTIN' | 'SIGTTOU' | 'SIGUNUSED' | 'SIGURG' | 'SIGUSR1' | 'SIGUSR2' | 'SIGVTALRM' | 'SIGWINCH' | 'SIGXCPU' | 'SIGXFSZ' | 'SIGBREAK' | 'SIGLOST' | 'SIGINFO') => Promise<void>;
              dispose: () => void | Promise<void>;
            }>;
          };
          readonly log?: /* ILogger — packages/agent-core-v2/src/_base/log/log.ts */ {
            error: (message: string, payload?: unknown) => void;
            warn: (message: string, payload?: unknown) => void;
            info: (message: string, payload?: unknown) => void;
            debug: (message: string, payload?: unknown) => void;
            child: (ctx: /* LogContext — packages/agent-core-v2/src/_base/log/log.ts */ {
              [key: string]: unknown;
            }) => /* ILogger — recursive (packages/agent-core-v2/src/_base/log/log.ts) */ unknown;
          };
        }) => Promise<string>;
        readonly summaryPolicy?: /* AgentProfileSummaryPolicy — packages/agent-core-v2/src/app/agentProfileCatalog/agentProfileCatalog.ts */ {
          readonly minChars: number;
          readonly continuationPrompt: string;
          readonly retries: number;
        };
      }[];
      readonly skipped?: readonly /* SkippedAgentFile — packages/agent-core-v2/src/app/agentFileCatalog/types.ts */ {
        readonly path: string;
        readonly reason: string;
      }[];
      readonly scannedRoots?: readonly string[];
    };
    readonly priority: number;
  }>;
  'sessionAgentProfileCatalog.merged': Map<string, /* AgentProfile — packages/agent-core-v2/src/app/agentProfileCatalog/agentProfileCatalog.ts */ {
    readonly name: string;
    readonly description?: string;
    readonly whenToUse?: string;
    readonly override?: boolean;
    readonly tools?: readonly string[];
    readonly disallowedTools?: readonly string[];
    readonly subagents?: readonly string[];
    readonly modelPreference?: 'primary' | 'secondary';
    systemPrompt: (context: /* AgentProfileContext — packages/agent-core-v2/src/app/agentProfileCatalog/agentProfileCatalog.ts */ {
      readonly cwd?: string;
      readonly cwdListing?: string;
      readonly agentsMd?: string;
      readonly additionalDirsInfo?: string;
      readonly osKind?: string;
      readonly shellName?: string;
      readonly shellPath?: string;
      readonly now?: string;
      readonly skills?: string;
      readonly skillActive?: boolean;
      readonly pluginSections?: string;
      [key: string]: unknown;
    }) => string;
    readonly promptPrefix?: (ctx: /* AgentProfilePromptPrefixContext — packages/agent-core-v2/src/app/agentProfileCatalog/agentProfileCatalog.ts */ {
      readonly cwd: string;
      readonly runner: /* ISessionProcessRunner — packages/agent-core-v2/src/session/process/processRunner.ts */ {
        readonly _serviceBrand: undefined;
        exec: (args: readonly string[], options?: /* ProcessExecOptions — packages/agent-core-v2/src/session/process/processRunner.ts */ {
          readonly cwd?: string;
          readonly env?: Record<string, string>;
        }) => Promise</* IProcess — packages/agent-core-v2/src/session/process/processRunner.ts */ {
          readonly stdin: Writable;
          readonly stdout: Readable;
          readonly stderr: Readable;
          readonly pid: number;
          readonly exitCode: number | null;
          wait: () => Promise<number>;
          kill: (signal?: 'SIGABRT' | 'SIGALRM' | 'SIGBUS' | 'SIGCHLD' | 'SIGCONT' | 'SIGFPE' | 'SIGHUP' | 'SIGILL' | 'SIGINT' | 'SIGIO' | 'SIGIOT' | 'SIGKILL' | 'SIGPIPE' | 'SIGPOLL' | 'SIGPROF' | 'SIGPWR' | 'SIGQUIT' | 'SIGSEGV' | 'SIGSTKFLT' | 'SIGSTOP' | 'SIGSYS' | 'SIGTERM' | 'SIGTRAP' | 'SIGTSTP' | 'SIGTTIN' | 'SIGTTOU' | 'SIGUNUSED' | 'SIGURG' | 'SIGUSR1' | 'SIGUSR2' | 'SIGVTALRM' | 'SIGWINCH' | 'SIGXCPU' | 'SIGXFSZ' | 'SIGBREAK' | 'SIGLOST' | 'SIGINFO') => Promise<void>;
          dispose: () => void | Promise<void>;
        }>;
      };
      readonly log?: /* ILogger — packages/agent-core-v2/src/_base/log/log.ts */ {
        error: (message: string, payload?: unknown) => void;
        warn: (message: string, payload?: unknown) => void;
        info: (message: string, payload?: unknown) => void;
        debug: (message: string, payload?: unknown) => void;
        child: (ctx: /* LogContext — packages/agent-core-v2/src/_base/log/log.ts */ {
          [key: string]: unknown;
        }) => /* ILogger — recursive (packages/agent-core-v2/src/_base/log/log.ts) */ unknown;
      };
    }) => Promise<string>;
    readonly summaryPolicy?: /* AgentProfileSummaryPolicy — packages/agent-core-v2/src/app/agentProfileCatalog/agentProfileCatalog.ts */ {
      readonly minChars: number;
      readonly continuationPrompt: string;
      readonly retries: number;
    };
  }>;
  // src/session/sessionFs/fsService.ts
  'sessionFs.realRootsCache': {
    readonly key: string;
    readonly roots: readonly string[];
  } | undefined;
  'sessionFs.rgResolution': /* RgResolution — packages/agent-core-v2/src/session/sessionFs/rgLocator.ts */ {
    readonly path: string;
    readonly source: /* RgResolutionSource — packages/agent-core-v2/src/session/sessionFs/rgLocator.ts */ 'system-path' | 'share-bin-cached';
  } | null | undefined;
  // src/session/sessionFs/fsWatchService.ts
  'sessionFsWatch.gitignoreLoaded': boolean;
  'sessionFsWatch.pending': /* FsChangeEntry — packages/agent-core-v2/src/session/sessionFs/fsWatch.ts */ {
    path: string;
    change: /* FsChangeAction — packages/agent-core-v2/src/session/sessionFs/fsWatch.ts */ 'created' | 'modified' | 'deleted';
    kind: /* FsChangeKind — packages/agent-core-v2/src/session/sessionFs/fsWatch.ts */ 'file' | 'directory' | 'symlink';
    size_delta?: number;
    etag?: string;
  }[];
  'sessionFsWatch.rawCount': number;
  'sessionFsWatch.truncated': boolean;
  'sessionFsWatch.watched': Set<string>;
  // src/session/sessionLog/sessionLogService.ts
  'sessionLog.rootLevel': /* LogLevelState — packages/agent-core-v2/src/_base/log/logService.ts */ {
    level: /* LogLevel — packages/agent-core-v2/src/_base/log/log.ts */ 'info' | 'off' | 'error' | 'warn' | 'debug';
  };
  // src/session/sessionMetadata/sessionMetadataService.ts
  'sessionMetadata.data': /* SessionMeta — packages/agent-core-v2/src/session/sessionMetadata/sessionMetadata.ts */ {
    readonly id: string;
    readonly version: 2;
    readonly title?: string;
    readonly isCustomTitle?: boolean;
    readonly lastPrompt?: string;
    readonly createdAt: number;
    readonly updatedAt: number;
    readonly archived: boolean;
    readonly cwd: string;
    readonly forkedFrom?: string;
    readonly agents: Readonly<Record<string, /* AgentMeta — packages/agent-core-v2/src/session/sessionMetadata/sessionMetadata.ts */ {
      readonly homedir?: string;
      readonly type?: 'main' | 'sub' | 'independent';
      readonly parentAgentId?: string | null;
      readonly forkedFrom?: string;
      readonly labels?: Readonly<Record<string, string>>;
      readonly swarmItem?: string;
    }>>;
    readonly custom: Record<string, unknown>;
  } | undefined;
  // src/session/sessionSkillCatalog/skillCatalogService.ts
  'sessionSkillCatalog.contributions': Map<string, {
    readonly c: /* SkillContribution — packages/agent-core-v2/src/app/skillCatalog/skillSource.ts */ {
      readonly skills: readonly /* SkillDefinition — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
        readonly name: string;
        readonly description: string;
        readonly path: string;
        readonly dir: string;
        readonly content: string;
        readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
          readonly name?: string;
          readonly description?: string;
          readonly type?: string;
          readonly whenToUse?: string;
          readonly disableModelInvocation?: boolean;
          readonly isSubSkill?: boolean;
          readonly safe?: boolean;
          readonly arguments?: string | readonly unknown[];
          [key: string]: unknown;
        };
        readonly source: /* SkillSource — packages/agent-core-v2/src/app/skillCatalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
        readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
          readonly id: string;
          readonly instructions?: string;
        };
        readonly mermaid?: string;
        readonly d2?: string;
      }[];
      readonly skipped?: readonly /* SkippedSkill — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
        readonly path: string;
        readonly type: string;
        readonly reason: string;
      }[];
      readonly scannedRoots?: readonly string[];
    };
    readonly priority: number;
  }>;
  'sessionSkillCatalog.merged': /* InMemorySkillCatalog — packages/agent-core-v2/src/app/skillCatalog/registry.ts */ {
    registerBuiltinSkill: (skill: /* SkillDefinition — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/app/skillCatalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
    }) => void;
    register: (skill: /* SkillDefinition — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/app/skillCatalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
    }, options?: {
      readonly replace?: boolean;
    }) => void;
    recordSkipped: (skills: readonly /* SkippedSkill — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
      readonly path: string;
      readonly type: string;
      readonly reason: string;
    }[]) => void;
    addRoots: (roots: readonly string[]) => void;
    getSkill: (name: string) => /* SkillDefinition — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/app/skillCatalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
    } | undefined;
    getPluginSkill: (pluginId: string, name: string) => /* SkillDefinition — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/app/skillCatalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
    } | undefined;
    renderSkillPrompt: (skill: /* SkillDefinition — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/app/skillCatalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
    }, rawArgs: string, context?: {
      readonly sessionId?: string;
    }) => string;
    listSkills: () => readonly /* SkillDefinition — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/app/skillCatalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
    }[];
    listInvocableSkills: () => readonly /* SkillDefinition — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/app/skillCatalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
    }[];
    getSkillRoots: () => readonly string[];
    getSkippedByPolicy: () => readonly /* SkippedSkill — packages/agent-core-v2/src/app/skillCatalog/types.ts */ {
      readonly path: string;
      readonly type: string;
      readonly reason: string;
    }[];
    getSkillsDescription: () => string;
    getModelSkillListing: () => string;
  };
  // src/session/sessionToolPolicy/sessionToolPolicyService.ts
  'sessionToolPolicy.state': /* SessionToolPolicyState — packages/agent-core-v2/src/session/sessionToolPolicy/sessionToolPolicyService.ts */ {
    readonly disabledTools: readonly string[];
  };
  // src/session/workspaceCommand/workspaceCommandService.ts
  'workspaceCommand.pendingMainInjections': (/* ContextMessage — packages/agent-core-v2/src/agent/contextMemory/types.ts */ /* Message — packages/agent-core-v2/src/llmProtocol/message.ts */ {
    readonly role: /* Role — packages/agent-core-v2/src/llmProtocol/message.ts */ 'user' | 'system' | 'assistant' | 'tool';
    readonly name?: string;
    readonly content: (/* ContentPart — packages/agent-core-v2/src/llmProtocol/message.ts */ /* TextPart — packages/agent-core-v2/src/llmProtocol/message.ts */ {
      type: 'text';
      text: string;
    } | /* ThinkPart — packages/agent-core-v2/src/llmProtocol/message.ts */ {
      type: 'think';
      think: string;
      encrypted?: string;
    } | /* ImageURLPart — packages/agent-core-v2/src/llmProtocol/message.ts */ {
      type: 'image_url';
      imageUrl: {
        url: string;
        id?: string;
      };
    } | /* AudioURLPart — packages/agent-core-v2/src/llmProtocol/message.ts */ {
      type: 'audio_url';
      audioUrl: {
        url: string;
        id?: string;
      };
    } | /* VideoURLPart — packages/agent-core-v2/src/llmProtocol/message.ts */ {
      type: 'video_url';
      videoUrl: {
        url: string;
        id?: string;
      };
    })[];
    readonly toolCalls: /* ToolCall — packages/agent-core-v2/src/llmProtocol/message.ts */ {
      type: 'function';
      id: string;
      name: string;
      arguments: string | null;
      extras?: Record<string, unknown>;
      _streamIndex?: string | number;
    }[];
    readonly toolCallId?: string;
    readonly partial?: boolean;
    readonly tools?: readonly /* Tool — packages/agent-core-v2/src/llmProtocol/tool.ts */ {
      name: string;
      description: string;
      parameters: Record<string, unknown>;
      deferred?: true;
    }[];
  } & {
    readonly id?: string;
    readonly providerMessageId?: string;
    readonly origin?: /* UserPromptOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'user';
    } | /* SkillActivationOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'skill_activation';
      readonly activationId: string;
      readonly skillName: string;
      readonly skillArgs?: string;
      readonly trigger: 'user-slash' | 'model-tool' | 'nested-skill';
      readonly skillType?: string;
      readonly skillPath?: string;
      readonly skillSource?: 'project' | 'user' | 'extra' | 'builtin';
    } | /* PluginCommandOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'plugin_command';
      readonly activationId: string;
      readonly pluginId: string;
      readonly commandName: string;
      readonly commandArgs?: string;
      readonly trigger: 'user-slash';
    } | /* InjectionOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'injection';
      readonly variant: string;
      readonly ownerPromptId?: string;
    } | /* ShellCommandOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'shell_command';
      readonly phase: 'input' | 'output';
      readonly isError?: boolean;
    } | /* CompactionSummaryOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'compaction_summary';
    } | /* SystemTriggerOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'system_trigger';
      readonly name: string;
    } | /* TaskOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'task';
      readonly taskId: string;
      readonly status: /* AgentTaskStatus — packages/agent-core-v2/src/agent/task/types.ts */ 'completed' | 'failed' | 'running' | 'timed_out' | 'killed' | 'lost';
      readonly notificationId: string;
    } | /* CronJobOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'cron_job';
      readonly jobId: string;
      readonly cron: string;
      readonly recurring: boolean;
      readonly coalescedCount: number;
      readonly stale: boolean;
    } | /* CronMissedOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'cron_missed';
      readonly count: number;
    } | /* HookResultOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'hook_result';
      readonly event: string;
      readonly blocked?: boolean;
    } | /* RetryOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'retry';
      readonly trigger?: string;
    };
    readonly isError?: boolean;
    readonly note?: string;
    readonly toolCallDisplays?: Readonly<Record<string, /* ToolInputDisplay — packages/agent-core-v2/src/tool/toolInputDisplay.ts */ {
      kind: 'command';
      command: string;
      cwd?: string;
      description?: string;
      language?: 'bash';
    } | {
      kind: 'file_io';
      operation: 'read' | 'write' | 'edit' | 'glob' | 'grep';
      path: string;
      detail?: string;
      content?: string;
      before?: string;
      after?: string;
    } | {
      kind: 'diff';
      path: string;
      before: string;
      after: string;
      hunks?: number;
    } | {
      kind: 'search';
      query: string;
      scope?: string;
    } | {
      kind: 'url_fetch';
      url: string;
      method?: string;
    } | {
      kind: 'agent_call';
      agent_name: string;
      prompt: string;
      background?: boolean;
    } | {
      kind: 'skill_call';
      skill_name: string;
      args?: string;
    } | {
      kind: 'todo_list';
      items: {
        title: string;
        status: string;
      }[];
    } | {
      kind: 'task';
      task_id: string;
      status: string;
      description: string;
      task_kind?: string;
    } | {
      kind: 'task_stop';
      task_id: string;
      task_description: string;
    } | {
      kind: 'plan_review';
      plan: string;
      path?: string;
      options?: readonly {
        label: string;
        description: string;
      }[];
    } | {
      kind: 'goal_start';
      objective: string;
      completionCriterion?: string;
      mode: 'manual' | 'yolo';
    } | {
      kind: 'generic';
      summary: string;
      detail?: unknown;
    }>>;
  })[];
  // src/session/workspaceContext/workspaceContextService.ts
  'workspaceContext.additionalDirs': string[];
  'workspaceContext.workDir': string;
}

export type SessionStateKey = keyof SessionStateSnapshot;

/** Agent-scope keys registered into IAgentStateService. */
export interface AgentStateSnapshot {
  // src/agent/activityView/activityViewService.ts
  'activityView.background': Map<string, /* BackgroundRef — packages/agent-core-v2/src/agent/activityView/activityView.ts */ {
    readonly kind: string;
    readonly id: string;
    readonly since: number;
  }>;
  'activityView.current': /* AgentActivityState — packages/agent-core-v2/src/agent/activityView/activityView.ts */ {
    readonly lifecycle: /* ActivityViewLifecycle — packages/agent-core-v2/src/agent/activityView/activityView.ts */ 'ready' | 'disposed';
    readonly turn?: /* ActivityTurnState — packages/agent-core-v2/src/agent/activityView/activityView.ts */ {
      readonly turnId: number;
      readonly origin: /* PromptOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ /* UserPromptOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'user';
      } | /* SkillActivationOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'skill_activation';
        readonly activationId: string;
        readonly skillName: string;
        readonly skillArgs?: string;
        readonly trigger: 'user-slash' | 'model-tool' | 'nested-skill';
        readonly skillType?: string;
        readonly skillPath?: string;
        readonly skillSource?: 'project' | 'user' | 'extra' | 'builtin';
      } | /* PluginCommandOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'plugin_command';
        readonly activationId: string;
        readonly pluginId: string;
        readonly commandName: string;
        readonly commandArgs?: string;
        readonly trigger: 'user-slash';
      } | /* InjectionOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'injection';
        readonly variant: string;
        readonly ownerPromptId?: string;
      } | /* ShellCommandOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'shell_command';
        readonly phase: 'input' | 'output';
        readonly isError?: boolean;
      } | /* CompactionSummaryOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'compaction_summary';
      } | /* SystemTriggerOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'system_trigger';
        readonly name: string;
      } | /* TaskOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'task';
        readonly taskId: string;
        readonly status: /* AgentTaskStatus — packages/agent-core-v2/src/agent/task/types.ts */ 'completed' | 'failed' | 'running' | 'timed_out' | 'killed' | 'lost';
        readonly notificationId: string;
      } | /* CronJobOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'cron_job';
        readonly jobId: string;
        readonly cron: string;
        readonly recurring: boolean;
        readonly coalescedCount: number;
        readonly stale: boolean;
      } | /* CronMissedOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'cron_missed';
        readonly count: number;
      } | /* HookResultOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'hook_result';
        readonly event: string;
        readonly blocked?: boolean;
      } | /* RetryOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'retry';
        readonly trigger?: string;
      };
      readonly phase: /* TurnPhase — packages/agent-core-v2/src/agent/activityView/activityView.ts */ 'running' | 'streaming' | 'tool_call' | 'retrying';
      readonly stream?: 'assistant' | 'tool_call' | 'thinking';
      readonly step: number;
      readonly ending: boolean;
      readonly endingReason?: 'error' | 'aborted' | 'max_steps';
      readonly retry?: /* ActivityRetryState — packages/agent-core-v2/src/agent/activityView/activityView.ts */ {
        readonly failedAttempt: number;
        readonly nextAttempt: number;
        readonly maxAttempts: number;
        readonly delayMs: number;
        readonly errorName?: string;
        readonly statusCode?: number;
      };
      readonly pendingApprovals: readonly /* ApprovalRef — packages/agent-core-v2/src/agent/activityView/activityView.ts */ {
        readonly approvalId: string;
        readonly toolCallId?: string;
        readonly since: number;
      }[];
      readonly activeToolCalls: readonly /* ToolCallRef — packages/agent-core-v2/src/agent/activityView/activityView.ts */ {
        readonly toolCallId: string;
        readonly name: string;
        readonly since: number;
      }[];
      readonly since: number;
    };
    readonly lastTurn?: /* ActivityLastTurnState — packages/agent-core-v2/src/agent/activityView/activityView.ts */ {
      readonly turnId: number;
      readonly reason: /* TurnEndReason — packages/agent-core-v2/src/agent/loop/turnEvents.ts */ 'completed' | 'cancelled' | 'failed' | 'blocked';
      readonly durationMs?: number;
      readonly at: number;
    };
    readonly background: readonly /* BackgroundRef — packages/agent-core-v2/src/agent/activityView/activityView.ts */ {
      readonly kind: string;
      readonly id: string;
      readonly since: number;
    }[];
  };
  'activityView.lastTurn': /* ActivityLastTurnState — packages/agent-core-v2/src/agent/activityView/activityView.ts */ {
    readonly turnId: number;
    readonly reason: /* TurnEndReason — packages/agent-core-v2/src/agent/loop/turnEvents.ts */ 'completed' | 'cancelled' | 'failed' | 'blocked';
    readonly durationMs?: number;
    readonly at: number;
  } | undefined;
  'activityView.lifecycle': /* ActivityViewLifecycle — packages/agent-core-v2/src/agent/activityView/activityView.ts */ 'ready' | 'disposed';
  'activityView.turn': /* MutableTurn — packages/agent-core-v2/src/agent/activityView/activityViewService.ts */ {
    phase: /* TurnPhase — packages/agent-core-v2/src/agent/activityView/activityView.ts */ 'running' | 'streaming' | 'tool_call' | 'retrying';
    stream: 'assistant' | 'tool_call' | 'thinking' | undefined;
    step: number;
    ending: boolean;
    endingReason: 'error' | 'aborted' | 'max_steps' | undefined;
    retry: /* ActivityRetryState — packages/agent-core-v2/src/agent/activityView/activityView.ts */ {
      readonly failedAttempt: number;
      readonly nextAttempt: number;
      readonly maxAttempts: number;
      readonly delayMs: number;
      readonly errorName?: string;
      readonly statusCode?: number;
    } | undefined;
    pendingApprovals: Map<string, /* ApprovalRef — packages/agent-core-v2/src/agent/activityView/activityView.ts */ {
      readonly approvalId: string;
      readonly toolCallId?: string;
      readonly since: number;
    }>;
    activeToolCalls: Map<string, /* ToolCallRef — packages/agent-core-v2/src/agent/activityView/activityView.ts */ {
      readonly toolCallId: string;
      readonly name: string;
      readonly since: number;
    }>;
    since: number;
    turnId: number;
    origin: /* PromptOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ /* UserPromptOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'user';
    } | /* SkillActivationOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'skill_activation';
      readonly activationId: string;
      readonly skillName: string;
      readonly skillArgs?: string;
      readonly trigger: 'user-slash' | 'model-tool' | 'nested-skill';
      readonly skillType?: string;
      readonly skillPath?: string;
      readonly skillSource?: 'project' | 'user' | 'extra' | 'builtin';
    } | /* PluginCommandOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'plugin_command';
      readonly activationId: string;
      readonly pluginId: string;
      readonly commandName: string;
      readonly commandArgs?: string;
      readonly trigger: 'user-slash';
    } | /* InjectionOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'injection';
      readonly variant: string;
      readonly ownerPromptId?: string;
    } | /* ShellCommandOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'shell_command';
      readonly phase: 'input' | 'output';
      readonly isError?: boolean;
    } | /* CompactionSummaryOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'compaction_summary';
    } | /* SystemTriggerOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'system_trigger';
      readonly name: string;
    } | /* TaskOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'task';
      readonly taskId: string;
      readonly status: /* AgentTaskStatus — packages/agent-core-v2/src/agent/task/types.ts */ 'completed' | 'failed' | 'running' | 'timed_out' | 'killed' | 'lost';
      readonly notificationId: string;
    } | /* CronJobOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'cron_job';
      readonly jobId: string;
      readonly cron: string;
      readonly recurring: boolean;
      readonly coalescedCount: number;
      readonly stale: boolean;
    } | /* CronMissedOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'cron_missed';
      readonly count: number;
    } | /* HookResultOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'hook_result';
      readonly event: string;
      readonly blocked?: boolean;
    } | /* RetryOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
      readonly kind: 'retry';
      readonly trigger?: string;
    };
    snapshot: () => /* ActivityTurnState — packages/agent-core-v2/src/agent/activityView/activityView.ts */ {
      readonly turnId: number;
      readonly origin: /* PromptOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ /* UserPromptOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'user';
      } | /* SkillActivationOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'skill_activation';
        readonly activationId: string;
        readonly skillName: string;
        readonly skillArgs?: string;
        readonly trigger: 'user-slash' | 'model-tool' | 'nested-skill';
        readonly skillType?: string;
        readonly skillPath?: string;
        readonly skillSource?: 'project' | 'user' | 'extra' | 'builtin';
      } | /* PluginCommandOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'plugin_command';
        readonly activationId: string;
        readonly pluginId: string;
        readonly commandName: string;
        readonly commandArgs?: string;
        readonly trigger: 'user-slash';
      } | /* InjectionOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'injection';
        readonly variant: string;
        readonly ownerPromptId?: string;
      } | /* ShellCommandOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'shell_command';
        readonly phase: 'input' | 'output';
        readonly isError?: boolean;
      } | /* CompactionSummaryOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'compaction_summary';
      } | /* SystemTriggerOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'system_trigger';
        readonly name: string;
      } | /* TaskOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'task';
        readonly taskId: string;
        readonly status: /* AgentTaskStatus — packages/agent-core-v2/src/agent/task/types.ts */ 'completed' | 'failed' | 'running' | 'timed_out' | 'killed' | 'lost';
        readonly notificationId: string;
      } | /* CronJobOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'cron_job';
        readonly jobId: string;
        readonly cron: string;
        readonly recurring: boolean;
        readonly coalescedCount: number;
        readonly stale: boolean;
      } | /* CronMissedOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'cron_missed';
        readonly count: number;
      } | /* HookResultOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'hook_result';
        readonly event: string;
        readonly blocked?: boolean;
      } | /* RetryOrigin — packages/agent-core-v2/src/agent/contextMemory/types.ts */ {
        readonly kind: 'retry';
        readonly trigger?: string;
      };
      readonly phase: /* TurnPhase — packages/agent-core-v2/src/agent/activityView/activityView.ts */ 'running' | 'streaming' | 'tool_call' | 'retrying';
      readonly stream?: 'assistant' | 'tool_call' | 'thinking';
      readonly step: number;
      readonly ending: boolean;
      readonly endingReason?: 'error' | 'aborted' | 'max_steps';
      readonly retry?: /* ActivityRetryState — packages/agent-core-v2/src/agent/activityView/activityView.ts */ {
        readonly failedAttempt: number;
        readonly nextAttempt: number;
        readonly maxAttempts: number;
        readonly delayMs: number;
        readonly errorName?: string;
        readonly statusCode?: number;
      };
      readonly pendingApprovals: readonly /* ApprovalRef — packages/agent-core-v2/src/agent/activityView/activityView.ts */ {
        readonly approvalId: string;
        readonly toolCallId?: string;
        readonly since: number;
      }[];
      readonly activeToolCalls: readonly /* ToolCallRef — packages/agent-core-v2/src/agent/activityView/activityView.ts */ {
        readonly toolCallId: string;
        readonly name: string;
        readonly since: number;
      }[];
      readonly since: number;
    };
  } | undefined;
  // src/agent/contextInjector/contextInjectorService.ts
  'contextInjector.isNewTurn': boolean;
  // src/agent/contextProjector/contextProjectorService.ts
  'contextProjector.lastRepairSignature': string | null;
  // src/agent/contextSize/contextSizeService.ts
  'contextSize.lastEmittedTokens': number;
  // src/agent/externalHooks/externalHooksService.ts
  'externalHooks.stopHookContinuationUsed': boolean;
  // src/agent/faultInjection/faultInjectionService.ts
  'faultInjection.armed': 'request-too-large' | 'image-format' | undefined;
  'faultInjection.fired': (/* FaultKind — packages/agent-core-v2/src/agent/faultInjection/faultInjection.ts */ 'request-too-large' | 'image-format')[];
  // src/agent/fullCompaction/fullCompactionService.ts
  'fullCompaction.activeTurnId': number | undefined;
  'fullCompaction.compactionCountInTurn': number;
  'fullCompaction.consecutiveOverflowCompactions': number;
  'fullCompaction.lastCompactedTokenCount': number | null;
  'fullCompaction.observedMaxContextTokensByModel': Map<string, number>;
  // src/agent/goal/goalService.ts
  'goal.budgetGraceTurns': Set<number>;
  'goal.countedGoalTurns': Set<number>;
  'goal.exhaustedTurnBudgetGoals': Map<number, string>;
  'goal.goalDrivenTurns': Map<number, string>;
  'goal.goalOutcomeContinuationTurns': Set<number>;
  'goal.goalOutcomeToolResultTurns': Map<number, string>;
  'goal.goalStarterTurns': Set<number>;
  'goal.goalTurnTargets': Map<number, string>;
  'goal.liveTurnId': number | undefined;
  'goal.liveWallClockStartedAt': number | undefined;
  'goal.pendingContinuationGoals': Map<number, string>;
  'goal.resumeContinuation': /* ResumeContinuation — packages/agent-core-v2/src/agent/goal/goalService.ts */ {
    readonly turnId: number;
    readonly goalId: string;
  } | undefined;
  // src/agent/llmRequester/llmRequesterService.ts
  'llmRequester.emittedThinkingEffortWarnings': Set<string>;
  'llmRequester.lastConfigLogSignature': string | undefined;
  'llmRequester.mediaDegradedTurns': Set<number>;
  'llmRequester.mediaStrippedTurns': Map<number, /* MediaStripSnapshot — packages/agent-core-v2/src/agent/contextProjector/contextProjector.ts */ {
    readonly "__@mediaStripSnapshotBrand@2689": undefined;
  }>;
  'llmRequester.turnConfigs': Map<number, /* TurnRequestConfig — packages/agent-core-v2/src/agent/llmRequester/llmRequesterService.ts */ {
    readonly resolved: /* ProfileModelContext — packages/agent-core-v2/src/agent/profile/profile.ts */ {
      readonly modelAlias: string;
      readonly modelCapabilities: /* ModelCapability — packages/agent-core-v2/src/llmProtocol/capability.ts */ {
        readonly image_in: boolean;
        readonly video_in: boolean;
        readonly audio_in: boolean;
        readonly thinking: boolean;
        readonly tool_use: boolean;
        readonly max_context_tokens: number;
        readonly max_input_tokens?: number;
        readonly dynamically_loaded_tools?: boolean;
      };
      readonly maxOutputSize: number | undefined;
      readonly alwaysThinking: boolean | undefined;
      readonly thinkingLevel: /* ThinkingEffort — packages/agent-core-v2/src/llmProtocol/provider.ts */ 'off' | 'on' | (string & {});
      readonly reservedContextSize: number | undefined;
      readonly compactionTriggerRatio: number | undefined;
    };
    readonly params: /* ModelRequestParams — packages/agent-core-v2/src/app/modelCatalog/modelRequester.ts */ {
      readonly cacheKey?: string;
      readonly sampling?: /* SamplingOptions — packages/agent-core-v2/src/llmProtocol/provider.ts */ {
        readonly temperature?: number;
        readonly topP?: number;
      };
      readonly thinkingEffort?: 'off' | 'on' | (string & {});
      readonly thinkingKeep?: string;
      readonly maxCompletionTokens?: number;
      readonly usedContextTokens?: number;
      readonly maxContextTokens?: number;
      readonly onTraceId?: (traceId: string | null) => void;
    };
    readonly systemPrompt: string;
  }>;
  // src/agent/loop/loopService.ts
  'loop.disposing': boolean;
  'loop.lastRequestTraceId': string | undefined;
  'loop.nextReservedTurnId': number | undefined;
  // src/agent/mcp/mcpService.ts
  'mcp.discoveryWritesReady': boolean;
  'mcp.mcpToolsByServer': Map<string, string[]>;
  // src/agent/media/mediaToolsRegistrar.ts
  'media.registeredKey': string | undefined;
  // src/agent/permissionMode/injection/permissionModeInjection.ts
  'permissionMode.lastMode': 'manual' | 'yolo' | 'auto' | undefined;
  // src/agent/plan/injection/planModeInjection.ts
  'plan.wasActive': boolean;
  // src/agent/profile/profileService.ts
  'profile.activeToolNamesOverlay': readonly string[] | undefined;
  'profile.agentsMdWarning': string | undefined;
  'profile.emittedPluginBudgetWarnings': Set<string>;
  'profile.emittedThinkingEffortWarnings': Set<string>;
  'profile.emittedToolPatternWarnings': Set<string>;
  // src/agent/prompt/promptService.ts
  'prompt.launching': boolean;
  // src/agent/shellCommand/shellCommandService.ts
  'shellCommand.tasks': Map<string, string>;
  // src/agent/stepRetry/stepRetryService.ts
  'stepRetry.failedAttempts': number;
  'stepRetry.lastFailedDriverId': string | undefined;
  // src/agent/task/taskService.ts
  'task.activeTaskReminderPending': boolean;
  'task.deliveredNotificationKeys': Set<string>;
  'task.ghosts': Map<string, /* AgentTaskInfo — packages/agent-core-v2/src/agent/task/types.ts */ /* QuestionTaskInfo — packages/agent-core-v2/src/agent/tools/ask-user-question/question-background-task.ts */ {
    readonly kind: 'question';
    readonly questionCount: number;
    readonly toolCallId?: string;
    readonly taskId: string;
    readonly description: string;
    readonly status: /* AgentTaskStatus — packages/agent-core-v2/src/agent/task/types.ts */ 'completed' | 'failed' | 'running' | 'timed_out' | 'killed' | 'lost';
    readonly detached?: boolean;
    readonly startedAt: number;
    readonly endedAt: number | null;
    readonly stopReason?: string;
    readonly terminalNotificationSuppressed?: boolean;
    readonly timeoutMs?: number;
  } | /* ToolAgentTaskInfo — packages/agent-core-v2/src/agent/task/types.ts */ {
    readonly kind: 'tool';
    readonly turnId: number;
    readonly toolCallId: string;
    readonly toolName: string;
    readonly autoWaitTimeoutSeconds: number;
    readonly taskId: string;
    readonly description: string;
    readonly status: /* AgentTaskStatus — packages/agent-core-v2/src/agent/task/types.ts */ 'completed' | 'failed' | 'running' | 'timed_out' | 'killed' | 'lost';
    readonly detached?: boolean;
    readonly startedAt: number;
    readonly endedAt: number | null;
    readonly stopReason?: string;
    readonly terminalNotificationSuppressed?: boolean;
    readonly timeoutMs?: number;
  } | /* SubagentTaskInfo — packages/agent-core-v2/src/agent/tools/agent/subagent-task.ts */ {
    readonly kind: 'agent';
    readonly agentId?: string;
    readonly subagentType?: string;
    readonly taskId: string;
    readonly description: string;
    readonly status: /* AgentTaskStatus — packages/agent-core-v2/src/agent/task/types.ts */ 'completed' | 'failed' | 'running' | 'timed_out' | 'killed' | 'lost';
    readonly detached?: boolean;
    readonly startedAt: number;
    readonly endedAt: number | null;
    readonly stopReason?: string;
    readonly terminalNotificationSuppressed?: boolean;
    readonly timeoutMs?: number;
  } | /* ProcessTaskInfo — packages/agent-core-v2/src/agent/tools/os/bash/process-task.ts */ {
    readonly kind: 'process';
    readonly command: string;
    readonly pid: number;
    readonly exitCode: number | null;
    readonly taskId: string;
    readonly description: string;
    readonly status: /* AgentTaskStatus — packages/agent-core-v2/src/agent/task/types.ts */ 'completed' | 'failed' | 'running' | 'timed_out' | 'killed' | 'lost';
    readonly detached?: boolean;
    readonly startedAt: number;
    readonly endedAt: number | null;
    readonly stopReason?: string;
    readonly terminalNotificationSuppressed?: boolean;
    readonly timeoutMs?: number;
  }>;
  'task.scheduledNotificationKeys': Set<string>;
  // src/agent/toolDedupe/toolDedupeService.ts
  'toolDedupe.activeStep': number;
  'toolDedupe.activeTurnId': number | undefined;
  'toolDedupe.callKeyByCallId': Map<string, string>;
  'toolDedupe.consecutiveCount': number;
  'toolDedupe.consecutiveKey': string | null;
  'toolDedupe.originalCallIndex': Map<string, number>;
  'toolDedupe.stepCalls': string[];
  'toolDedupe.syntheticCallIds': Set<string>;
  // src/agent/toolExecutor/toolExecutorService.ts
  'toolExecutor.dupTypeTurnId': number | undefined;
  'toolExecutor.toolCallDupTypes': Map<string, /* ToolCallDupType — packages/agent-core-v2/src/agent/toolExecutor/toolExecutor.ts */ 'same_step' | 'cross_step'>;
  // src/agent/toolSelect/toolSelectAnnouncementsService.ts
  'toolSelect.needsBoundaryInjection': boolean;
  // src/agent/toolSelect/toolSelectService.ts
  'toolSelect.pendingLoaded': Set<string>;
  // src/agent/usage/usageService.ts
  'usage.currentTurn': /* TokenUsage — packages/agent-core-v2/src/llmProtocol/usage.ts */ {
    inputOther: number;
    output: number;
    inputCacheRead: number;
    inputCacheCreation: number;
  } | undefined;
  'usage.currentTurnId': number | undefined;
}

export type AgentStateKey = keyof AgentStateSnapshot;
