// Wire Protocol Manifest
//
// Generated by scripts/gen-wire-manifest.mts — do not edit by hand.
// Regenerate with: pnpm --filter @dimi-ai/agent-core-v2 gen:wire-manifest
//
// protocol_version: "1.5" (migrations: 1.0 -> 1.1 -> 1.2 -> 1.3 -> 1.4 -> 1.5)
//
// One declaration per record type registered via defineOp(...) and drained from
// the runtime OP_REGISTRY. Every payload declaration carries its record type in
// a `_name` field. Payload sketches use TypeScript type syntax; when a
// named type is expanded inline, its name appears as a doc comment
// (`/** ContextMessage */`). Bare type names (ContentPart, ContextMessage, …)
// refer to the real types in src/ — they are intentionally not resolved here.
// `// …` marks a capped field list. On disk (wire.jsonl) the journal opens with
// a metadata line {"type": "metadata", "protocol_version", "created_at"}; each
// op record is {"type", ...payload, "time"} — object payloads spread at the
// top level, scalar payloads nest under a "payload" key.
//
// Declaration flags: persisted (written to the journal; absent = transient),
// toEvent (also publishes an IEventBus fact on live dispatch), blobs (the
// owning model offloads inline media to blob storage), cross-reducers
// (foreign models that also reduce this record on dispatch and replay).

// Index (46 record types)
//   config.update                      profile              persisted  (unresolved)
//   context_size.measured              contextSize          transient  src/agent/contextSize/contextSizeOps.ts
//   context.append_loop_event          contextMemory        persisted  (unresolved)
//   context.append_message             contextMemory        persisted  (unresolved)
//   context.apply_compaction           contextMemory        persisted  (unresolved)
//   context.clear                      contextMemory        persisted  (unresolved)
//   context.undo                       contextMemory        persisted  (unresolved)
//   cron.add                           cron                 transient  src/session/cron/cronOps.ts
//   cron.cursor                        cron                 transient  src/session/cron/cronOps.ts
//   cron.delete                        cron                 transient  src/session/cron/cronOps.ts
//   forked                             goal                 persisted  src/agent/goal/goalOps.ts
//   full_compaction.begin              fullCompaction       persisted  src/agent/fullCompaction/compactionOps.ts
//   full_compaction.cancel             fullCompaction       persisted  src/agent/fullCompaction/compactionOps.ts
//   full_compaction.complete           fullCompaction       persisted  src/agent/fullCompaction/compactionOps.ts
//   goal.clear                         goal                 persisted  src/agent/goal/goalOps.ts
//   goal.create                        goal                 persisted  src/agent/goal/goalOps.ts
//   goal.update                        goal                 persisted  src/agent/goal/goalOps.ts
//   interaction.request                interaction          persisted  src/session/interaction/interactionOps.ts
//   interaction.resolved               interaction          persisted  src/session/interaction/interactionOps.ts
//   llm.request                        llm.requestTrace     persisted  (unresolved)
//   llm.tools_snapshot                 llm.requestTrace     persisted  (unresolved)
//   mcp.tools_discovered               mcp.discovery        persisted  src/agent/mcp/mcpDiscoveryOps.ts
//   permission.record_approval_result  permissionRules      persisted  src/agent/permissionRules/permissionRulesOps.ts
//   permission.rules.add               permissionRules      transient  src/agent/permissionRules/permissionRulesOps.ts
//   permission.set_mode                permissionMode       persisted  src/agent/permissionMode/permissionModeOps.ts
//   plan_mode.cancel                   plan                 persisted  src/agent/plan/planOps.ts
//   plan_mode.enter                    plan                 persisted  src/agent/plan/planOps.ts
//   plan_mode.exit                     plan                 persisted  src/agent/plan/planOps.ts
//   plan.revision                      plan                 persisted  src/agent/plan/planOps.ts
//   profile.bind                       profile              persisted  (unresolved)
//   skill.activate                     skill                transient  src/agent/skill/skillOps.ts
//   swarm_mode.enter                   swarm                persisted  src/agent/swarm/swarmOps.ts
//   swarm_mode.exit                    swarm                persisted  src/agent/swarm/swarmOps.ts
//   task.started                       task                 persisted  src/agent/task/taskOps.ts
//   task.terminated                    task                 persisted  src/agent/task/taskOps.ts
//   tools.register_user_tool           userTool             persisted  src/agent/userTool/userToolOps.ts
//   tools.reset_active_tools           profile.activeTools  persisted  (unresolved)
//   tools.set_active_tools             profile.activeTools  persisted  (unresolved)
//   tools.unregister_user_tool         userTool             persisted  src/agent/userTool/userToolOps.ts
//   tools.update_store                 todo                 persisted  src/session/todo/todoOps.ts
//   turn.cancel                        turn                 persisted  (unresolved)
//   turn.prompt                        turn                 persisted  (unresolved)
//   turn.steer                         turn                 persisted  (unresolved)
//   usage.record                       usage                persisted  (unresolved)
//   wait.started                       wait                 persisted  src/agent/wait/wait.ts
//   wait.terminated                    wait                 persisted  src/agent/wait/wait.ts

/**
 * model: profile · persisted
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface ConfigUpdatePayload {
  _name: 'config.update';
}

/**
 * model: contextSize · toEvent
 * owner: src/agent/contextSize/contextSizeOps.ts
 */
interface ContextSizeMeasuredPayload {
  _name: 'context_size.measured';
  length: number;
  tokens: number;
}

/**
 * model: contextMemory · persisted · blobs · cross-reducers: turn
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface ContextAppendLoopEventPayload {
  _name: 'context.append_loop_event';
}

/**
 * model: contextMemory · persisted · blobs · cross-reducers: plan, goalForkNotice, task.notificationDelivery, todo
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface ContextAppendMessagePayload {
  _name: 'context.append_message';
}

/**
 * model: contextMemory · persisted · blobs · cross-reducers: plan, task.notificationDelivery, todo
 * owner: (unresolved)
 */
interface ContextApplyCompactionPayload {
  _name: 'context.apply_compaction';
  summary: string;
  contextSummary: string;
  compactedCount: number;
  tokensBefore: number;
  tokensAfter: number;
  keptUserMessageCount: number;
  keptHeadUserMessageCount?: number;
  droppedCount?: number;
}

/**
 * model: contextMemory · persisted · blobs · cross-reducers: plan, task.notificationDelivery, todo
 * owner: (unresolved)
 */
interface ContextClearPayload {
  _name: 'context.clear';
}

/**
 * model: contextMemory · persisted · blobs · cross-reducers: plan, task.notificationDelivery, todo
 * owner: (unresolved)
 */
interface ContextUndoPayload {
  _name: 'context.undo';
  count: number;
}

/**
 * model: cron
 * owner: src/session/cron/cronOps.ts
 */
interface CronAddPayload {
  _name: 'cron.add';
  /** CronTask */
  task: {
    id: string;
    cron: string;
    prompt: string;
    createdAt: number;
    recurring?: boolean;
    lastFiredAt?: number;
    tags?: Readonly<Record<string, string>>;
  };
}

/**
 * model: cron
 * owner: src/session/cron/cronOps.ts
 */
interface CronCursorPayload {
  _name: 'cron.cursor';
  id: string;
  lastFiredAt: number;
}

/**
 * model: cron
 * owner: src/session/cron/cronOps.ts
 */
interface CronDeletePayload {
  _name: 'cron.delete';
  ids: string[];
}

/**
 * model: goal · persisted · cross-reducers: goalForkNotice
 * owner: src/agent/goal/goalOps.ts
 */
interface ForkedPayload {
  _name: 'forked';
}

/**
 * model: fullCompaction · persisted · toEvent
 * owner: src/agent/fullCompaction/compactionOps.ts
 * payload type: CompactionBeginData
 */
interface FullCompactionBeginPayload {
  _name: 'full_compaction.begin';
  instruction?: string;
  source: 'manual' | 'auto';
}

/**
 * model: fullCompaction · persisted
 * owner: src/agent/fullCompaction/compactionOps.ts
 */
interface FullCompactionCancelPayload {
  _name: 'full_compaction.cancel';
}

/**
 * model: fullCompaction · persisted
 * owner: src/agent/fullCompaction/compactionOps.ts
 */
interface FullCompactionCompletePayload {
  _name: 'full_compaction.complete';
}

/**
 * model: goal · persisted · cross-reducers: goalForkNotice
 * owner: src/agent/goal/goalOps.ts
 */
interface GoalClearPayload {
  _name: 'goal.clear';
}

/**
 * model: goal · persisted · cross-reducers: goalForkNotice
 * owner: src/agent/goal/goalOps.ts
 */
interface GoalCreatePayload {
  _name: 'goal.create';
  goalId: string;
  objective: string;
  completionCriterion?: string;
  wallClockResumedAt?: number;
  status?: 'active' | 'paused' | 'blocked' | 'complete';
  actor?: 'user' | 'model' | 'runtime' | 'system';
  budgetLimits?: {
    tokenBudget?: number;
    turnBudget?: number;
    wallClockBudgetMs?: number;
  };
}

/**
 * model: goal · persisted
 * owner: src/agent/goal/goalOps.ts
 */
interface GoalUpdatePayload {
  _name: 'goal.update';
  goalId?: string;
  status?: 'active' | 'paused' | 'blocked' | 'complete';
  reason?: string;
  turnsUsed?: number;
  tokensUsed?: number;
  wallClockMs?: number;
  wallClockResumedAt?: number;
  budgetLimits?: {
    tokenBudget?: number;
    turnBudget?: number;
    wallClockBudgetMs?: number;
  };
  actor?: 'user' | 'model' | 'runtime' | 'system';
}

/**
 * model: interaction · persisted
 * owner: src/session/interaction/interactionOps.ts
 */
interface InteractionRequestPayload {
  _name: 'interaction.request';
  id: string;
  kind: 'approval' | 'question' | 'user_tool';
  toolCallId?: string;
  agentId?: string;
  request: any;
}

/**
 * model: interaction · persisted
 * owner: src/session/interaction/interactionOps.ts
 */
interface InteractionResolvedPayload {
  _name: 'interaction.resolved';
  id: string;
  response: any;
}

/**
 * model: llm.requestTrace · persisted
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface LlmRequestPayload {
  _name: 'llm.request';
}

/**
 * model: llm.requestTrace · persisted
 * owner: (unresolved)
 */
interface LlmToolsSnapshotPayload {
  _name: 'llm.tools_snapshot';
  hash: string;
  tools: {
    name: string;
    description: string;
    parameters: Record<string, any>;
  }[];
}

/**
 * model: mcp.discovery · persisted
 * owner: src/agent/mcp/mcpDiscoveryOps.ts
 */
interface McpToolsDiscoveredPayload {
  _name: 'mcp.tools_discovered';
  serverName: string;
  hash: string;
  tools: readonly MCPToolDefinition[];
  enabledNames: string[];
  collisions?: {
    qualified: string;
    toolName: string;
    collidesWith: { kind: 'same_server', toolName: string } | { kind: 'other_server', serverName: string };
  }[];
}

/**
 * model: permissionRules · persisted
 * owner: src/agent/permissionRules/permissionRulesOps.ts
 * payload type: PermissionApprovalResultRecord
 */
interface PermissionRecordApprovalResultPayload {
  _name: 'permission.record_approval_result';
  turnId: number;
  toolCallId: string;
  toolName: string;
  action: string;
  sessionApprovalRule?: string;
  result: ApprovalResponse;
}

/**
 * model: permissionRules
 * owner: src/agent/permissionRules/permissionRulesOps.ts
 */
interface PermissionRulesAddPayload {
  _name: 'permission.rules.add';
  rules: readonly PermissionRule[];
}

/**
 * model: permissionMode · persisted · cross-reducers: permissionMode.configured
 * owner: src/agent/permissionMode/permissionModeOps.ts
 */
interface PermissionSetModePayload {
  _name: 'permission.set_mode';
  /** PermissionMode */
  mode: 'manual' | 'yolo' | 'auto';
}

/**
 * model: plan · persisted · toEvent
 * owner: src/agent/plan/planOps.ts
 */
interface PlanModeCancelPayload {
  _name: 'plan_mode.cancel';
  id?: string;
}

/**
 * model: plan · persisted · toEvent
 * owner: src/agent/plan/planOps.ts
 */
interface PlanModeEnterPayload {
  _name: 'plan_mode.enter';
  id: string;
}

/**
 * model: plan · persisted · toEvent
 * owner: src/agent/plan/planOps.ts
 */
interface PlanModeExitPayload {
  _name: 'plan_mode.exit';
  id?: string;
}

/**
 * model: plan · persisted · toEvent
 * owner: src/agent/plan/planOps.ts
 */
interface PlanRevisionPayload {
  _name: 'plan.revision';
  id: string;
  version: number;
  path: string;
  sha256: string;
  bytes: number;
}

/**
 * model: profile · persisted · cross-reducers: profile.activeTools
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface ProfileBindPayload {
  _name: 'profile.bind';
}

/**
 * model: skill · toEvent
 * owner: src/agent/skill/skillOps.ts
 */
interface SkillActivatePayload {
  _name: 'skill.activate';
  /** SkillActivationOrigin */
  origin: {
    kind: "skill_activation";
    activationId: string;
    skillName: string;
    skillArgs?: string | undefined;
    trigger: "user-slash" | "model-tool" | "nested-skill";
    skillType?: string | undefined;
    skillPath?: string | undefined;
    skillSource?: "project" | "user" | "extra" | "builtin" | undefined;
  };
}

/**
 * model: swarm · persisted · toEvent
 * owner: src/agent/swarm/swarmOps.ts
 */
interface SwarmModeEnterPayload {
  _name: 'swarm_mode.enter';
  /** SwarmModeTrigger */
  trigger: 'manual' | 'task' | 'tool';
}

/**
 * model: swarm · persisted · toEvent · cross-reducers: contextMemory
 * owner: src/agent/swarm/swarmOps.ts
 */
interface SwarmModeExitPayload {
  _name: 'swarm_mode.exit';
}

/**
 * model: task · persisted · toEvent
 * owner: src/agent/task/taskOps.ts
 */
interface TaskStartedPayload {
  _name: 'task.started';
  /** AgentTaskInfo */
  info: AgentTaskInfoByKind[AgentTaskKind];
}

/**
 * model: task · persisted · toEvent
 * owner: src/agent/task/taskOps.ts
 */
interface TaskTerminatedPayload {
  _name: 'task.terminated';
  /** AgentTaskInfo */
  info: AgentTaskInfoByKind[AgentTaskKind];
  outputTail?: string;
}

/**
 * model: userTool · persisted
 * owner: src/agent/userTool/userToolOps.ts
 * payload type: UserToolRegistration
 */
interface ToolsRegisterUserToolPayload {
  _name: 'tools.register_user_tool';
  name: string;
  description: string;
  parameters: Record<string, unknown>;
  disclosure?: "inline" | "deferred";
}

/**
 * model: profile.activeTools · persisted
 * owner: (unresolved)
 */
interface ToolsResetActiveToolsPayload {
  _name: 'tools.reset_active_tools';
}

/**
 * model: profile.activeTools · persisted
 * owner: (unresolved)
 */
interface ToolsSetActiveToolsPayload {
  _name: 'tools.set_active_tools';
  names: string[];
}

/**
 * model: userTool · persisted
 * owner: src/agent/userTool/userToolOps.ts
 */
interface ToolsUnregisterUserToolPayload {
  _name: 'tools.unregister_user_tool';
  name: string;
}

/**
 * model: todo · persisted
 * owner: src/session/todo/todoOps.ts
 */
interface ToolsUpdateStorePayload {
  _name: 'tools.update_store';
  key: string;
  value: any;
}

/**
 * model: turn · persisted
 * owner: (unresolved)
 */
interface TurnCancelPayload {
  _name: 'turn.cancel';
  turnId?: number;
  target?: 'active' | 'queued';
}

/**
 * model: turn · persisted
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface TurnPromptPayload {
  _name: 'turn.prompt';
}

/**
 * model: turn · persisted
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface TurnSteerPayload {
  _name: 'turn.steer';
}

/**
 * model: usage · persisted
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface UsageRecordPayload {
  _name: 'usage.record';
}

/**
 * model: wait · persisted · toEvent
 * owner: src/agent/wait/wait.ts
 */
interface WaitStartedPayload {
  _name: 'wait.started';
  wait: {
    waitId: string;
    reason: string;
    source: 'wait_for' | 'auto_wait';
    timeoutSeconds: number;
    startedAt: number;
    deadlineAt: number;
    turnId?: number;
    taskIds?: string[];
  };
}

/**
 * model: wait · persisted · toEvent
 * owner: src/agent/wait/wait.ts
 */
interface WaitTerminatedPayload {
  _name: 'wait.terminated';
  wait: {
    waitId: string;
    reason: string;
    source: 'wait_for' | 'auto_wait';
    timeoutSeconds: number;
    startedAt: number;
    deadlineAt: number;
    turnId?: number;
    taskIds?: string[];
  };
  reason: 'notification' | 'message' | 'timeout';
}

/** Record type → payload sketch. */
interface WirePayloadMap {
  "config.update": ConfigUpdatePayload;
  "context_size.measured": ContextSizeMeasuredPayload;
  "context.append_loop_event": ContextAppendLoopEventPayload;
  "context.append_message": ContextAppendMessagePayload;
  "context.apply_compaction": ContextApplyCompactionPayload;
  "context.clear": ContextClearPayload;
  "context.undo": ContextUndoPayload;
  "cron.add": CronAddPayload;
  "cron.cursor": CronCursorPayload;
  "cron.delete": CronDeletePayload;
  "forked": ForkedPayload;
  "full_compaction.begin": FullCompactionBeginPayload;
  "full_compaction.cancel": FullCompactionCancelPayload;
  "full_compaction.complete": FullCompactionCompletePayload;
  "goal.clear": GoalClearPayload;
  "goal.create": GoalCreatePayload;
  "goal.update": GoalUpdatePayload;
  "interaction.request": InteractionRequestPayload;
  "interaction.resolved": InteractionResolvedPayload;
  "llm.request": LlmRequestPayload;
  "llm.tools_snapshot": LlmToolsSnapshotPayload;
  "mcp.tools_discovered": McpToolsDiscoveredPayload;
  "permission.record_approval_result": PermissionRecordApprovalResultPayload;
  "permission.rules.add": PermissionRulesAddPayload;
  "permission.set_mode": PermissionSetModePayload;
  "plan_mode.cancel": PlanModeCancelPayload;
  "plan_mode.enter": PlanModeEnterPayload;
  "plan_mode.exit": PlanModeExitPayload;
  "plan.revision": PlanRevisionPayload;
  "profile.bind": ProfileBindPayload;
  "skill.activate": SkillActivatePayload;
  "swarm_mode.enter": SwarmModeEnterPayload;
  "swarm_mode.exit": SwarmModeExitPayload;
  "task.started": TaskStartedPayload;
  "task.terminated": TaskTerminatedPayload;
  "tools.register_user_tool": ToolsRegisterUserToolPayload;
  "tools.reset_active_tools": ToolsResetActiveToolsPayload;
  "tools.set_active_tools": ToolsSetActiveToolsPayload;
  "tools.unregister_user_tool": ToolsUnregisterUserToolPayload;
  "tools.update_store": ToolsUpdateStorePayload;
  "turn.cancel": TurnCancelPayload;
  "turn.prompt": TurnPromptPayload;
  "turn.steer": TurnSteerPayload;
  "usage.record": UsageRecordPayload;
  "wait.started": WaitStartedPayload;
  "wait.terminated": WaitTerminatedPayload;
}
