packages:
  - packages/*
  - apps/*
  - docs

catalog:
  zod: 4.3.6

overrides:
  "dimi>@tailwindcss/vite": "4.1.18"
  "ssh2@1.17.0>cpu-features": "-"
  "ssh2@1.17.0>nan": "-"
  "dimi>tailwindcss": "4.1.18"
