/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 03889f01dbdc66d4240110327c7e200a)
interface __BaseEnv_Env {
	BUILDS: R2Bucket;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
