name: Feature Request
description: Propose a new feature for Dimi
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Is Dimi missing a feature that you'd like to see? Feel free to propose it here.

        Before you submit a feature:
        1. Search existing issues for similar features. If you find one, 👍 it rather than opening a new one.
        2. The Dimi team will try to balance the varying needs of the community when prioritizing or rejecting new features. Please understand that not all features will be accepted.
        3. Do not open a feature PR until maintainers have had a chance to respond here. PRs without prior discussion may be closed without review.

  - type: textarea
    id: feature
    attributes:
      label: What feature would you like to see?
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional information
      description: Is there anything else you think we should know?
