/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1f4452783da8f7f1a79ccf66524ffbdb)
interface __BaseEnv_Env {
	RELAY_ROOMS: DurableObjectNamespace<import("./src/index").RelayRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RelayRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
